---
apiVersion: v1
kind: Secret
metadata:
  name: cedricclyburn-demo-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-gh/cedricclyburn-demo-backend-gitops
